### ISSUE TITLE
syntax highlighting errors in conditionals

### ISSUE THREAD

**Issue by PierBover** [SublimeText/Astro#11]
I'm seeing these weird errors in valid syntax when using conditionals.

<img width="1044" alt="image" src="https://github.com/user-attachments/assets/5801955a-de48-40e1-a85b-ba31b428ffb2">

Or see how the syntax color change depending on the element order:

<img width="882" alt="image" src="https://github.com/user-attachments/assets/0292743c-d289-4529-a5dc-bd3cc8930cdc">

**Comment by FichteFoll** [comment]
When reporting highlighting issues, please include code samples in plain text for reproduction.

**Comment by PierBover** [comment]
Sorry, you're right.

```
	{VITE_USE_VITE_WEB_COMPONENTS && (
		<script type="module" src="http://localhost:5173/@vite/client" is:inline></script>
		<script type="module" src="http://localhost:5173/src/main.js" is:inline></script>
	)}
```

```
		{DEV && (
			<wavekit-ribbon audio-id="7SHuksjXYA" border="false"/>
			<wavekit-ribbon audio-id="7SHuksjXYA" border="false"/>
			<wavekit-ribbon audio-id="7SHuksjXYA" border="false"/>
			<wavekit-ribbon audio-id="7SHuksjXYA" border="false"/>
			<wavekit-ribbon audio-id="7SHuksjXYA" border="false"/>
			<wavekit-ribbon audio-id="7SHuksjXYA" border="false"/>
			<wavekit-ribbon audio-id="7SHuksjXYA" border="false"/>
		)}
```
