### ISSUE TITLE
Template literals with a variable expression breaks syntax

### ISSUE THREAD

**Issue by magnusdahlstrand** [SublimeText/Astro#2]
<img width="393" alt="Screenshot 2022-10-04 at 17 30 17" src="https://user-images.githubusercontent.com/1193414/193876251-e317e5dd-20fd-4606-8435-035b39bfc513.png">

Minimal example:
```astro
---
import Layout from '../layouts/Layout.astro';
const title = 'Example text';
---

<Layout title={`${title} | Website`}>
</Layout>
```

The closing bracket of `${title}` is interpreted as the closing bracket for the prop's value (and therefore the string), which causes code after it to be interpreted as a new string, which it is not.

In the code above the template string can be constructed in the code fence section at the top, so this is more of an issue for code like:

```astro
---
import Layout from '../layouts/Layout.astro';
const slugs = ['a', 'b', 'c'];
---

<Layout>
	{slugs.map((slug) => (
		<div data-id={slug}>
			<PostLink
				href={`/post/${slug}`}
			/>
		</div>
	))}
</Layout>
```

<img width="390" alt="Screenshot 2022-10-04 at 17 50 33" src="https://user-images.githubusercontent.com/1193414/193879381-6cfa8a87-bc10-45a4-b9c6-9dc26233b4b5.png">

Although writing that example, the issue seems to arise at the closing bracket in `data-id={slug}`, so there seems to be something up with the closing bracket in general.

**Comment by deathaxe** [comment]
This bug is fixed in Astro 2.0.0, which requires at least ST4126+.

It won't be fixed in Astro 1.x
