### ISSUE TITLE
Frontmatter Syntax Highlighting

### ISSUE THREAD

**Issue by Deester4x4jr** [SublimeText/Astro#3]
Just curious, are you using a specific color scheme to get the frontmatter area to properly highlight syntax? For some reason, mine is always just a single color. I've tried over a dozen different flavors of monokai, plus a few others.

![image](https://user-images.githubusercontent.com/7119208/198074612-3c81f5cf-8c0e-463a-89cd-5fd25e4dea20.png)

**Comment by deathaxe** [comment]
Frontmatter is highlighted using TypeScript syntax with main scope `source.ts`.

It should be present as it is a default syntax of ST4.

---

Please note Astro 2.0 syntax requires ST4126+.

All earlier ST builds get Atro v1.2 which may have several issues. 

v1.x is no longer maintained.

**Comment by naranyala** [comment]
FYI, I'm on linux where tried to install sublime with `snap` package manager but I had the same problem, my solution was try to install the official `.deb` package from sublime site, and frontmatter came back highlighted
