### ISSUE TITLE
Latest release (2.1.2) breaks JS/TS syntax highlighting with ST3 TypeScript package installed

### ISSUE THREAD

**Issue by phortuin** [SublimeText/Astro#5]
## Actual behaviour
Syntax highlighting breaks (as in, no syntax highlighting) for JS/TS. See image: all TypeScript in frontmatter and templates renders as black, without syntax highlighting.

![image](https://github.com/SublimeText/Astro/assets/137299/818f4eb3-3560-43a6-ba22-d4bf968e8d7f)

## What did I expect
The TS in the frontmatter block should have syntax highlighting, as should the inline TS in the template. 

## How to reproduce
Not sure, but installing a previous version of the package (copying `Astro-2.1.1-st4134.sublime-package` to the Installed Packages folder of Sublime) fixes the problem:

![image](https://github.com/SublimeText/Astro/assets/137299/fcd69bef-954b-4094-a09e-6d791bfb20ea)

## More info
I am on Sublime Text build 4143 (Stable Channel), on MacOS 13.3.1 (a) on a 2020 MacBook Air M1. Some related packages I installed in Sublime are LSP, LSP-Astro, TypeScript and LSP-Typescript. The theme I use is Ayu Light with a custom color scheme.

Thanks!

**Comment by deathaxe** [comment]
Astro 2.1.2 embedds TypeScript (`source.ts`) in frontmatter and TSX (`source.tsx`) in interpolations, while previous versions used JavaScript and JSX.

This change was made as most Astro examples seem to use TypeScript.

All those syntaxes are shipped with ST4 and therefore are available by default.

Maybe you've got an 3rd-party TypeScript/TSX syntax installed, which occupies `source.ts` but does not provide the required `script` context:

https://github.com/SublimeText/Astro/blob/29ea1522715fb5ad2cf20f560e10230d4bf8b9af/Syntaxes/HTML%20(Astro).sublime-syntax#L42

https://github.com/SublimeText/Astro/blob/29ea1522715fb5ad2cf20f560e10230d4bf8b9af/Syntaxes/HTML%20(Astro).sublime-syntax#L470

To find them you can call `sublime.find_syntax_by_scope("source.ts")` in ST's console.

Here's a screenshot of ST4143 with only Astro installed:

![grafik](https://github.com/SublimeText/Astro/assets/16542113/c9ed0b61-6361-486f-8700-dd3c2b84e432)

**Comment by phortuin** [comment]
Awesome, I found out I still had the TypeScript package for ST3 installed (https://packagecontrol.io/packages/TypeScript). After uninstall that package and restarting Sublime, things worked as they should. I'll update this issue’s subject so that others can troubleshoot similar issues 👌
