### ISSUE TITLE
TypeScript syntax highlighting detection incompatible with Astro script processing

### ISSUE THREAD

**Issue by HereIsKevin** [SublimeText/Astro#7]
Hi,

While using Sublime Text 4143 on macOS Ventura 13.4, TypeScript syntax highlighting seems to be broken.
<img width="572" alt="Screenshot 2023-06-25 at 6 04 03 PM" src="https://github.com/SublimeText/Astro/assets/49735863/b6dce99a-f319-4108-93bc-e45d44c87357">

After adding `lang="ts"`, highlighting seems to work.
<img width="689" alt="Screenshot 2023-06-25 at 6 04 39 PM" src="https://github.com/SublimeText/Astro/assets/49735863/1f11d6e3-7701-44ab-90d2-ee9fc78e4064">

However, using attributes to detect TypeScript seems to break Astro's script bundling, as mentioned [here](https://docs.astro.build/en/guides/client-side-scripts/#script-bundling)

> NOTE
> Astro’s default bundling behavior will be disabled in some situations. In particular, adding type="module" or any attribute other than src to a <script> tag will cause Astro to treat the tag as if it had an is:inline directive. The same will be true when the script is written in a JSX expression.

This causes the script to be bundled as JavaScript, not as TypeScript, so it is never bundled.

I'm not sure how this could be fixed, but assuming that all scripts are TypeScript may be a potential solution, as TypeScript is a JavaScript superset, so could you look into that?

Thanks in advance!

**Comment by deathaxe** [comment]
Thank's for reporting. The next release declares TypeScript as default syntax in script tags.
