### ISSUE TITLE
No seeing any syntax high lighting at all

### ISSUE THREAD

**Issue by dotnetCarpenter** [SublimeText/Astro#8]
I have a freshly installed ST4 with Astro 2.1.4 plugin. And this (below) is what I see:
![image](https://github.com/SublimeText/Astro/assets/43763/0ad8b3ba-f379-4345-a147-47c5ebba1b89)

**Am I missing any steps?**

My project is inside WSL2 Ubuntu.
Syntax is set to Astro -> HTML (Astro) for _.astro_ files.

### Versions
Sublime Text: Build 4152
Plugins: Astro 2.1.4, LSP 1.25.0, LSP-astro 2.3.2
OS: Windows 10 1903 (10.0.18362.1256) with WSL2
node: v18.17.1
npm: 9.6.7
VM OS: Ubuntu 20.04.6 LTS

**Comment by deathaxe** [comment]
According to the status bar in the screenshot open file is assigned to _Plain Text_ syntax.

The file icons in sidebar however indicate ST knows about Astro files being of markup scope.

Astro just provides a syntax definition (_*.sublime-syntax_) which is assigned to _*.astro_ extension.

Installing only Astro on a fresh ST4152 results in all astro files being highlighted properly, when opening on my end. Location of open files doesn't matter as long as ST can open them.

As the sidebar icon looks reasonable, maybe a plugin is assigning syntax dynamically, after opening?

**Comment by dotnetCarpenter** [comment]
Well, I only have the plugins mentioned install, plus your WslBuild plugin.

Plugins: Astro 2.1.4, LSP 1.25.0, LSP-astro 2.3.2 and WslBuild 0.2.0

Clicking on the _"Plain Text"_ and choosing HTML (Astro) turns on syntax highlighting as expected. It's weird that choosing _View -> Syntax -> Astro -> HTML (Astro)_ does nothing.

Seems like a bug in ST4152

**Comment by deathaxe** [comment]
ST should open astro files using Astro syntax automatically, except something assigned *.astro to plain text via sublime-settings file.

You could look for syntax specific settings files in your _User_ package, which may contain a `"extensions": ["astro"]` entry or just use the "Open all with current extansion as..." submenu, to re-assign it.
