### ISSUE TITLE
Emmet does not work on files with .astro extension

### ISSUE THREAD

**Issue by Eliezer516** [SublimeText/Astro#9]
I need help with this, I installed the plugin but for some reason emmet does not work within the files.

When trying to create a div or any other tag, emmet does not "capture" said tag, I have to manually open and close all the tags I want to use.

I want to solve this, I really like Astro but working this way makes my performance very slow.

**Comment by deathaxe** [comment]
Astro files use `source.astro` main scope.

That's probably something which needs to be configured handled in Emmet.

The emmet author may be able to provide support.
